name: Node.js CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: npm install

      - name: Generate Deployment Package
        run: zip -r backend-server-build.zip .

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "nodetest"
          environment_name: "Nodetest-env-1"
          version_label: ${{ github.sha }}
          region: us-west-1
          deployment_package: backend-server-build.zip
          use_existing_version_if_available: true
